# Generated by Django 4.0.4 on 2022-04-18 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image_ur',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Ikea-Brooklyn-Warehouse-Aisles.jpg/640px-Ikea-Brooklyn-Warehouse-Aisles.jpg', max_length=400),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_ur',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Good_Food_Display_-_NCI_Visuals_Online.jpg/640px-Good_Food_Display_-_NCI_Visuals_Online.jpg', max_length=400),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 15, 12, 57, 260596)),
        ),
    ]
