# Generated by Django 4.1.7 on 2023-02-27 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_ingedient_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 14, 10, 14, 665926)),
        ),
        migrations.AddField(
            model_name='purchases',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='Ingredient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
