# Generated by Django 4.0.4 on 2022-04-18 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_ingredient_image_ur_menuitem_image_ur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='image_ur',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='image_ur',
            new_name='image_url',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 15, 13, 30, 365103)),
        ),
    ]
