# Generated by Django 4.1.7 on 2023-02-27 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_recipe_ingredient_alter_purchases_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 16, 2, 42, 658549)),
        ),
    ]
