# Generated by Django 4.1.7 on 2023-03-29 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_purchases_options_alter_purchases_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 20, 49, 56, 904377)),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['price'], name='inventory_i_price_f2b48d_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['stock'], name='inventory_i_stock_c4792d_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['price'], name='inventory_m_price_5ae8fc_idx'),
        ),
    ]
