# Generated by Django 4.1.7 on 2023-04-11 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_purchases_options_alter_purchases_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 14, 47, 44, 823292)),
        ),
    ]
