# Generated by Django 4.1.7 on 2023-04-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_purchases_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
